### ISSUE TITLE
TypeError in VideoData on branch 0.6.0 while running under python 2.7

### ISSUE THREAD

**Issue by ptrmu** [hanyazou/TelloPy#21]
Tello: 17:48:18.658: Error: video recv: unsupported operand type(s) for &: 'str' and 'int'
Traceback (most recent call last):
  File "/home/peter/Work/flock_catkin_ws/src/TelloPy/tellopy/_internal/tello.py", line 661, in __video_thread
    video_data = VideoData(data)
  File "/home/peter/Work/flock_catkin_ws/src/TelloPy/tellopy/_internal/protocol.py", line 234, in __init__
    if VideoData.packets_per_frame < (self.h1 & 0x7f):
TypeError: unsupported operand type(s) for &: 'str' and 'int'

**Comment by dsvilarkovic** [comment]
Yeah, I also have this thing when running this example on 0.6.0. Please respond!
