### ISSUE TITLE
Manage to run the testcode, but nothing is happening with Tello

### ISSUE THREAD

**Issue by monhelle** [hanyazou/TelloPy#58]
Hey

I am currently trying to get the tello to work with python. I've downloaded your zip folder and tried running the simple_takeoff-file, but it is only loading in the run window. Nothing is happening with the Tello that's on the ground.

1. I've downloaded what you said needed to be downloaded
2. I added the folder in the same location
3. I connected the tello to the wifi
4. The window is running, but nothing is happening. 
5. I also tried to change the ports and ip to 8888 and xxx.xxx.xx.2

What should I try?

**Comment by pnehareddy1** [comment]
hi, 

PLEASE HELP - I think you will have answer this issue - I am facing issue with connection issue when I ran the same script (simple_takeoff). Have TIME OUT issue. Checked firewall status (UFW) and it is INACTIVE.

HERE IS THE ACTIVITY IN THE TERMINAL I SEE:
********************************************************************************************
Tello: 00:24:35.545: Info: send connection request (cmd="conn_req:9617")
Tello: 00:24:35.545: Info: state transit State::disconnected -> State::connecting
Tello: 00:24:35.545: Info: start video thread
Tello: 00:24:35.545: Info: video receive buffer size = 425984
Tello: 00:24:37.547: Info: send connection request (cmd="conn_req:9617")
Tello: 00:24:39.550: Info: send connection request (cmd="conn_req:9617")
Tello: 00:24:41.552: Info: send connection request (cmd="conn_req:9617")
Tello: 00:24:43.555: Info: send connection request (cmd="conn_req:9617")
Tello: 00:24:45.556: Info: send connection request (cmd="conn_req:9617")
Tello: 00:24:47.559: Info: send connection request (cmd="conn_req:9617")
Tello: 00:24:49.562: Info: send connection request (cmd="conn_req:9617")
Tello: 00:24:51.563: Info: send connection request (cmd="conn_req:9617")
Tello: 00:24:53.564: Info: send connection request (cmd="conn_req:9617")
Tello: 00:24:55.567: Info: send connection request (cmd="conn_req:9617")
Tello: 00:24:57.570: Info: send connection request (cmd="conn_req:9617")
Tello: 00:24:59.572: Info: send connection request (cmd="conn_req:9617")
Tello: 00:25:01.575: Info: send connection request (cmd="conn_req:9617")
Tello: 00:25:03.578: Info: send connection request (cmd="conn_req:9617")
Tello: 00:25:05.580: Info: send connection request (cmd="conn_req:9617")
Tello: 00:25:07.583: Info: send connection request (cmd="conn_req:9617")
Tello: 00:25:09.584: Info: send connection request (cmd="conn_req:9617")
Tello: 00:25:11.587: Info: send connection request (cmd="conn_req:9617")
Tello: 00:25:13.590: Info: send connection request (cmd="conn_req:9617")
Tello: 00:25:15.592: Info: send connection request (cmd="conn_req:9617")
Tello: 00:25:17.595: Info: send connection request (cmd="conn_req:9617")
Tello: 00:25:19.598: Info: send connection request (cmd="conn_req:9617")
Tello: 00:25:21.601: Info: send connection request (cmd="conn_req:9617")
Tello: 00:25:23.603: Info: send connection request (cmd="conn_req:9617")
Tello: 00:25:25.606: Info: send connection request (cmd="conn_req:9617")
Tello: 00:25:27.609: Info: send connection request (cmd="conn_req:9617")
Tello: 00:25:29.611: Info: send connection request (cmd="conn_req:9617")
Tello: 00:25:31.614: Info: send connection request (cmd="conn_req:9617")
Tello: 00:25:33.617: Info: send connection request (cmd="conn_req:9617")
Traceback (most recent call last):
File "/home/neha/.local/lib/python2.7/site-packages/tellopy/examples/video_effect.py", line 15, in main
drone.wait_for_connection(60.0)
File "/home/neha/.local/lib/python2.7/site-packages/tellopy/_internal/tello.py", line 133, in wait_for_connection
raise error.TelloError('timeout')
TelloError: TelloError::timeout
TelloError::timeout
Tello: 00:25:35.546: Info: quit
Tello: 00:25:35.546: Info: state transit State::connecting -> State::quit
Tello: 00:25:35.613: Info: exit from the video thread.
Tello: 00:25:35.620: Info: exit from the recv thread.
********************************************************************************************

Thanks
